---
- name: Hello World!jj
  hosts: test
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
   - name: ensure apache is at the latest version
    yum: name=httpd state=latest
