---
- name: Hello World!jj
  hosts: test
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
  - name: install the latest version of Apache
      yum:
      name: httpd
      state: latest
