---
- name: Hello World!jj
  hosts: test
 
  tasks:
 
  - name: Hello World!
    yum: name=httpd state=latest
  - name: Open port 80
    firewalld: service=http permanent=true state=enabled
  - name: start the firewalld service
    service: name=firewalld state=restarted
